package Solved_026_050;

import java.util.Arrays;

/**
 * Pentagon numbers
 * Problem 44
 * 
 * Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten
 * pentagonal numbers are:
 * 
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 * 
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
 * 70 - 22 = 48, is not pentagonal.
 * 
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
 * difference are pentagonal and D = |Pk - Pj| is minimised; what is the value
 * of D?
 */
public class PE044_Pentagon_numbers {
	public static void main(String[] args) {
		long start = System.nanoTime();

		int[] pentagonal = new int[10000];

		for (int i = 1; i < 10000; i++) {
			pentagonal[i] = (i * 3 * i - i) / 2;
		}

		for (int i = 1; i < 10000; i++) {
			for (int j = 1; j < i; j++) {
				if (isPentagonal(pentagonal, pentagonal[i] + pentagonal[j])
						&& isPentagonal(pentagonal, pentagonal[i]
								- pentagonal[j])) {
					long end = System.nanoTime();
					long runtime = end - start;
					System.out.println(pentagonal[i] - pentagonal[j]);
					System.out.println("Runtime: " + runtime / 1000000 + "ms ("
							+ runtime + "ns)");
					System.exit(0);
				}
			}
		}
	}

	private static boolean isPentagonal(int[] pentagonal, int value) {
		if (Arrays.binarySearch(pentagonal, value) >= 0) {
			return true;
		} else {
			return false;
		}
	}
}
