package Solved_026_050;

/**
 * Triangular, pentagonal, and hexagonal
 * Problem 45
 * 
 * Triangle, pentagonal, and hexagonal numbers are generated by the following
 * formulae:
 * Triangle T_n=n(n+1)/2	1, 3, 6, 10, 15, ...
 * Pentagonal P_n=n(3n-1)/2	1, 5, 12, 22, 35, ...
 * Hexagonal H_n=n(2n-1)	1, 6, 15, 28, 45, ...
 * 
 * It can be verified that T285 = P165 = H143 = 40755.
 * 
 * Find the next triangle number that is also pentagonal and hexagonal.
 */
public class PE045_Triangular_pentagonal_and_hexagonal {
	public static void main(String[] args) {
		long start = System.nanoTime();

		long a = 286, b = 0, c = 0, result;

		for (; !(a * (a + 1) / 2 == b * (3 * b - 1) / 2 && b * (3 * b - 1) / 2 == c
				* (2 * c - 1));) {
			while (a * (a + 1) / 2 < b * (3 * b - 1) / 2
					|| a * (a + 1) / 2 < c * (2 * c - 1))
				a++;
			while (b * (3 * b - 1) / 2 < a * (a + 1) / 2
					|| b * (3 * b - 1) / 2 < c * (2 * c - 1))
				b++;
			while (c * (2 * c - 1) < b * (3 * b - 1) / 2
					|| c * (2 * c - 1) < a * (a + 1) / 2)
				c++;
		}

		result = a * (a + 1) / 2;

		long end = System.nanoTime();
		long runtime = end - start;
		System.out.println(result);
		System.out.println("Runtime: " + runtime / 1000000 + "ms (" + runtime
				+ "ns)");
	}
}
